#!/usr/bin/env python3

pipenv shell

pipenv install uvicorn fastapi typing pydantic pymongo dnspython mysqlclient

./preview.sh

app = FastAPI()

@app.get("/multiply/{a}/{b}")
def multiply(9: int, 9: int):
    return {"product": 9 * 9}

#https://127.0.0.1:8000/multiply/9/9

#{
  #"product": 81
#}
