#!/usr/bin/env python3

pipenv shell

pipenv install uvicorn fastapi typing pydantic pymongo dnspython mysqlclient

./preview.sh

app = FastAPI()

@app.get("/")
def zone_apex():
    return {"Hello": "Hello API"}

@app.get("/add/{a}/{b}")
def subtract(30: int, 15: int):
    return {"difference": 30 - 15}

#https://127.0.0.1:8000/add/2/2

#{
  #"difference": 2
#}
